services:
  backend-dev:
    container_name: taskapp-backend-dev
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env.dev
    volumes:
      - backend_data:/app/instance
    ports:
      - "5001:5000"   # external -> internal
    restart: always
    networks:
      - taskapp-network
    environment:
      DATABASE_URL: sqlite:///dev.db
    command: sh -c "flask db upgrade && flask run --host=0.0.0.0 --port=5000 --reload"

  frontend-dev:
    container_name: taskapp-frontend-dev
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"   
    command: npm start
    environment:
      CHOKIDAR_USEPOLLING: "true"
    networks: 
      - taskapp-network
    depends_on:
      - backend-dev
