services:
  # dev backend
  backend-dev:
    container_name: taskapp-backend-dev
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env.dev
    volumes:
      - ./backend:/app   # Mount backend code
    command: flask run --host=0.0.0.0 --port=5000 --reload
    ports:
      - "5001:5000"   # external 5001 -> internal 5000
    restart: always
    networks:
      - taskapp-network

  # dev frontend
  frontend-dev:
    container_name: taskapp-frontend-dev
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"   # Run dev server instead of Nginx
    command: npm start
    environment:
      CHOKIDAR_USEPOLLING: "true"
    networks: 
      - taskapp-network
    depends_on:
      - backend-dev
