version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: taskapp-backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      FLASK_ENV: production
      SECRET_KEY: ${SECRET_KEY:-dev-secret-key}
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    networks:
      - taskapp-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: taskapp-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - taskapp-network
    depends_on:
      - backend

networks:
  taskapp-network:
    driver: bridge
