version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: taskapp-backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - backend_data:/app/instance
    networks:
      - taskapp-network
    command: >
      sh -c "flask db upgrade &&
             gunicorn -b 0.0.0.0:5000 app:app --timeout 300 --log-level debug --capture-output --enable-stdio-inheritance"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: taskapp-frontend
    restart: unless-stopped
    expose:
      - "80"
    networks:
      - taskapp-network
    depends_on:
      - backend

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - "80:80"      # HTTP
      - "443:443"    # HTTPS
      - "81:81"      # Admin UI
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt
    networks:
      - taskapp-network

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    networks:
      - taskapp-network

networks:
  taskapp-network:
    driver: bridge

volumes:
  backend_data:
  npm_data:
  npm_letsencrypt:
  ollama_data: